apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: tekton-singlestep
spec:
  steps:
    - name: step-1
      image: docker.io/ubuntu
      command:
        - /bin/sh
      args:
        - -c 
        - "echo  This is a default Tekton pipeline. Tekton is working." 
    